
suppressMessages({
 suppressPackageStartupMessages({
  library(YESCDS)
library(survival)
library(geojsonio)
library(tibble)
library(dplyr)
library(plotly)
library(ggplot2)
library(ggbeeswarm)
library(DT)
library(htmltools)
library(sf)
data("woncan_meta", package="YESCDS")
data("woncan", package="YESCDS")
data("vjc_cancer_net", package="YESCDS")
littab = woncan |> select(MSA, `Cancer Sites`, Age.Adjusted.Rate) |> as.data.frame()
  })
data(canada_crude)
data(SEER_2018)
 })
