---
title: "D1 Clinical trials concepts"
shorttitle: "Clinical trials concepts"
author: "Vincent J. Carey, stvjc at channing.harvard.edu"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{D1 Clinical trials concepts}
  %\VignetteEncoding{UTF-8}
output:
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    theme: united
    toc: yes
---

```{r setup,echo=FALSE,results="hide"}
suppressMessages({
 suppressPackageStartupMessages({
  library(YESCDS)
library(tibble)
library(dplyr)
library(plotly)
library(ggplot2)
library(ggbeeswarm)
library(DT)
data(woncan_meta)
data(woncan)
littab = woncan |> select(MSA, `Cancer Sites`, Age.Adjusted.Rate) |> as.data.frame()
  })
 })
```

# Clinical trials for cancer treatments

- Despite massive investments in cancer research and treatment development,
cancer remains a leading cause of death

- We have examined many aspects of cancer's diversity
    - tissue of origin
    - somatic mutations
    - response to treatment

- The main modalities of medical response to cancer are
    - surgery
    - chemotherapy
    - radiation

- Each of these modalities has a collection of subtypes, and they are often used in combination

- How do doctors and patients navigate the available options?
    - Answer: interpret available data as evidence in favor of or against certain options

- The "gold standard" for evidence in medical decisionmaking is the randomized clinical trial (RCT)
    - Trials are generally preceded by "pre-clinical" studies of drugs or other treatment
techniques
    - Analysis of data in pre-clinical research often demands great versatility of the statisticians
and data scientists
        - such data are often sparse and noisy
        - ideally one integrates all available scientific information about the proposed alternative,
requiring extensive literature search and acquisition of public data

# Questions to answer in designing a clinical trial  [(Article)](https://www.cancer.org/treatment/treatments-and-side-effects/clinical-trials/what-you-need-to-know/phases-of-clinical-trials.html)

- What is the current standard of care?  
- What care outcomes do we want to improve, and how much improvement would could as a real advance?
    - Here risk-benefit comparison becomes important
- What is the proposed alternative?
- How do we determine a safe "dose" of the proposed alternative?
    - In the case of surgery this question may not make sense
- How do we verify that the proposed alternative has any effect at all?
- How do we measure the overall benefit conferred by using the alternative method?

# The typical strategy: Three phases
- Phase I: enroll healthy volunteers to do dose finding, assessing toxicity and side effects
- Phase II: enroll patients with the disease and administer the maximum tolerated dose
to establish that the new treatment has some beneficial effect
- Phase III: enroll patients with the disease, but set up a comparison of the new treatment
versus the standard of care
    - a design plan is produced detailing how many patients are to be enrolled, how
the treatments will be administered, and how the data will be analyzed 
    - patients are randomly assigned either the new treatment, or the standard of care
    - a Data Safety Monitoring Board will review study data periodically
        - studies may end prematurely if great benefit is seen early on, or if it appears no
benefit could be documented by continuing the trial

# Experimentation with human subjects is carefully regulated

The concept of [informed consent](https://www.cancer.org/treatment/treatments-and-side-effects/clinical-trials/what-you-need-to-know/what-does-a-clinical-trial-involve.html) is central in the implementation of
clinical trials.

The [Belmont report](https://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/index.html)
defined principles and guidelines for all human subjects research.
