name: Vignettes to ipynb

on: 
  workflow_dispatch: {}

jobs:
  buildipynb:
    container:
      image: bioconductor/yes-jupyter:21.10
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          Rscript -e 'BiocManager::install("AnVILPublish")'
          pip install notedown
          cd inst/scripts
          make prepare
          make gupdate
          make
          cd ../..
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate ipynb $(echo $(date +'%m-%d-%y-%H-%M-%S'))"
          git push
